services:
  betrast-server:
    build: 
      dockerfile: Dockerfile
      target: production
    environment:
      - PORT=${PORT}
    expose:
      - ${PORT}
    networks:
      - server_common

networks:
  server_common:
    external: true
